### ISSUE TITLE
rdtsc usage

### ISSUE THREAD

**Issue by chaitanyalala** [NetSys/bess#121]
Regarding -->
```
static inline uint64_t rdtsc(void)
{
        uint32_t hi, lo; 
        __asm__ __volatile__ ("rdtsc" : "=a"(lo), "=d"(hi));
        return (uint64_t)lo | ((uint64_t)hi << 32);
}

```
IIUC This code is being used to calculate time-stamps and use it in sched_loop. AFAIK rdtsc is prone to CPU instruction re-ordering and hence may not be accurate for time-stamping and thus people tend to use "rdtscp" or "mfence+rdtsc". ( http://stackoverflow.com/questions/12631856/difference-between-rdtscp-rdtsc-memory-and-cpuid-rdtsc )

Is use of rdtsc in bess, for time-stamping, a potential issue ?

**Comment by sangjinhan** [comment]
I decided to use vanilla rdtsc (without cpuid or memory fence), not rdtscp, because I felt like they did not justify the performance penalty. A few notes:
- With rdtscp, the cost of timestamping became so high that `perf` reported it as the single most expensive instruction of the entire process.
- With memory fence, which is much cheaper, still the number of cycles spent for scheduling doubled.
- The main usage of rdtsc in the scheduling loop is to measure the CPU usage of individual traffic classes. 
  - Our hope here is that the odd (inaccuracy caused by instruction reordering) doesn't favor any particular traffic classes over others.
  - I _guess_ even there are some small error (~10s of ns) for each data point, when millions of them are aggregated the overall accuracy should be good enough.
  - I do not have any strong evidences to support the above two points, though :)

**Comment by gmporter** [comment]
What is the best way to get O(1us) accurate wall clock time within BESS?

**Comment by barath** [comment]
You can access the thread-local `ctx` from any module to get `ctx.current_tsc()` and `ctx.current_ns()`, which get updated by the scheduler on every scheduler tick.  Unless your pipeline is really deep and takes more than 1us per packet batch, you should be fine.  You can see this in use in `modules/dump.cc`, for example.
