### ISSUE TITLE
Is there any way to use ZeroCopyVPort inside a container?

### ISSUE THREAD

**Issue by duanjp8617** [NetSys/bess#34]
Hi Sangjin,

I am using bess to build a cluster for running NFV applications. 

I create 2 ZeroCopyVport in the host and connect these 2 ZeroCopyVPort in the host. And I can successfully run /core/nvport/native_app/source.c and /core/nvport/native_app/sink.c from the host.

Then I create a docker container and try to run /core/nvport/native_app/source.c in side the container, but it doesn't work. The problem is that I can't successfully initialize DPDK EAL. 

I'm wondering if it is possible to use ZeroCopyVPort in the container? Do I need to mount some directories inside the file system?

**Comment by sangjinhan** [comment]
Hi,

I think the container should have access to the followings, in order to run as a secondary DPDK process (Fig 19.1, http://dpdk.org/doc/guides/prog_guide/multi_proc_support.html)

/var/run/.rte_*
/mnt/huge or /dev/hugepages (depending on your Linux distro)

I don't quite remember how but there should be a straightforward way to configure docker that expose host's directories to containers.

(Perhaps @apanda has some experience with running native apps in a container...?)

**Comment by apanda** [comment]
I had to map the following directories to get ZeroCopyVport working in a Container (syntax is host to container, you'd pass each of these with `-v` to Docker, and directories might be specific to Debian). The last one in particular is where Bess looks for metadata related to the Vport.

```
/sys/bus/pci/drivers:/sys/bus/pci/drivers 
/sys/kernel/mm/hugepages:/sys/kernel/mm/hugepages
/mnt/huge/:/mnt/huge
/dev:/dev 
/sys/devices/system/node:/sys/devices/system/node
/var/run:/var/run
/tmp/sn_vports:/tmp/sn_vports
```

Additionally, I had to run the container in privileged mode (`--privileged` to Docker), at which point you should be careful because you Container can do pretty much anything to the host. As far as I know this is a DPDK requirement.

Finally, your application needs to run as a secondary process in this case.

**Comment by duanjp8617** [comment]
Hi @apanda and @sangjinhan 

Your comments fix my problem, thank you very much!
