### ISSUE TITLE
How to enable more than two containers to communicate with each other via bess

### ISSUE THREAD

**Issue by 201528015059077** [NetSys/bess#37]
I have tried the module Split and Merge to do this task. But I don't know how to set the correct value of offset in Split to determine which ogate should the pkg send to.

![](http://oc15i8gxi.bkt.clouddn.com/image/bess_github/container_communicate_on_bess.png)

Are there any other ways (e.g. other modules) to do this task ?

**Comment by sangjinhan** [comment]
It depends on your switching scheme... One possible approach would be using the destination MAC address (like Ethernet switches) of packets. The L2Forward module will do the job (or alternatively you can use Split module with offset=0/size=6, which represents the destination MAC address).

You will need to configure the L2Forward module with MAC address + ogate pairs. Since the MAC address of vport is randomly generated unless you specify one, it is convenient to set a fixed address for each vport (add "mac_addr" argument to the VPort creation, see samples/vxlan.bess as an example).

This setup will enable static (= no MAC learning) Ethernet switching for unicast packets. Since ARP packets are not supported in this setup, you will configures static ARP entries for the containers (e.g., in vp1 you configure ARP entries of vp2, vp3, and vp4, ...)

**Comment by 201528015059077** [comment]
Thanks a lot!
