### ISSUE TITLE
Issues with Mellanox NIC rx queue setup

### ISSUE THREAD

**Issue by srcvirus** [NetSys/bess#407]
Hello,

We are trying to run bess on a machine that has a single port Mellanox ConnectX-3 NIC. We were able to run bessd and detect the mellanox port. But when we are trying to create a PMDPort from bessctl CLI (add port PMDPort pport0 port_id=0) an exception is being thrown. We traced back the root of the reason and it seems rte_eth_rx_queue_setup is returning -EINVAL, i.e., "The size of network buffers which can be allocated from the memory pool does not fit the various buffer sizes allowed by the device controller". Any suggestions as to what configuration/parameter in bess might be causing this problem?

**Comment by sangjinhan** [comment]
Sorry for this late answer. It took me for a while to find a system with Mellanox NICs.

It turned out that the mlx4 (for the ConnectX-3 family) DPDK driver does not initialize correctly if the hugepages are not contiguous in the virtual memory. This usually happens the kernel cannot find a large memory chunk due to fragmentation, when hugepages are set (e.g., `sysctl vm.nr_hugepages=1024`).

Perhaps the easiest way to work around this issue is to configure 1GB hugepages at kernel boot time, rather than 2MB ones. For BESS you will need one 1GB hugepage for each CPU socket. Please refer to this page for more details: http://dpdk.org/doc/guides/linux_gsg/sys_reqs.html
