### ISSUE TITLE
Is there way to load compiled module?

### ISSUE THREAD

**Issue by GalSagie** [NetSys/bess#502]
Is there a way to compile a module into shared lib and then load these modules at start without
having to compile or add their source code?

I think i saw something like this added, can you please share instructions how to do it?
If not i would like to contribute such code.

**Comment by changlan** [comment]
Currently you can add source code into the `modules` directory and then `make modules` will build them into shared libraries. Shared libraries inside `modules` will be loaded at start. Is this something you are looking for?

**Comment by nemethf** [comment]
Sorry to butt in, but in most cases the `module_msg.proto` should be updated as well, shouldn't it?

**Comment by GalSagie** [comment]
changlan, yes this is what i was looking for.
nemethf, i believe this is true

**Comment by nrdmao** [comment]
By virtue of having to modify module_msg.proto aren't you 'having to
compile or add their source code' (see original request by GalSagie).

I think what is really being asked for is some type of module plugin
architecture that will load a .so or collection thereof that implements a
BESS module. Such a .so would include the .proto generated code so that the
user supplied module could be plugged into the bess infrastructure without
having to recompile bessd or modify the global module_msg.proto file.

Thanks,

Jim

**Comment by changlan** [comment]
(Reopening for further discussion)

Oh, I see the question. You could create standalone `*_msg.proto` for each custom module. However, this would not solve the problem because we currently do not link the related part of compiled protobuf/gRPC code (the part that handles custom module message parsing) into module dynamic libraries.

What the current code does is linking everything into `bessd`, which makes `bessd` dependent on the module-specific codes. So yes, it would be great to have a better module architecture.

Note that the Python side of the code still requires rebuilding BESS to work with custom modules correctly though.

**Comment by GalSagie** [comment]
This was recently solved (sample_plugin)
