### ISSUE TITLE
create vport refactor

### ISSUE THREAD

**Issue by muraliran** [NetSys/bess#843]
Looking at commit 49ac0958cdd0808729c03e12918c94eaf3f178e6

What was the reason to remove mac address setting? Just for my knowledge

**Comment by sangjinhan** [comment]
The mac address setting is still there, but refactored. Instead of specifying all configuration arguments (including MAC address) for `create_port`, now all runtime-configurable things are set *after* creating a port. https://github.com/NetSys/bess/commit/49ac0958cdd0808729c03e12918c94eaf3f178e6#diff-02af88de764f4ace536fffeace5795d1R255
