### ISSUE TITLE
vhost-user hugetable with memory usage

### ISSUE THREAD

**Issue by konnekapm** [NetSys/bess#846]
We are trying to use BESS for our qemu instances high bandwidth communications.
While opening qemu guests we are using below parameters,

_-m 512 \
-chardev socket,id=mychr,path=/tmp/bess_vhost1.sock \
-netdev vhost-user,id=mydev,chardev=mychr,vhostforce,queues=1 \
-device virtio-net-pci,netdev=mydev,mac=00:00:00:00:00:01 \
 -object memory-backend-file,id=mem,size=512M,mem-path=/mnt/huge,share=on \
-numa node,memdev=mem -mem-prealloc_

and we are getting high performance results.

But when we want to add additional ram space to guests (without using hugetblfs) , we cannot communicate between guests.

we tried to add below parameters, It boots, but no ping

_-object memory-backend-ram,id=mem2,size=2G,prealloc=on \
-numa node,memdev=mem2_ 

Do you have any idea how can we add additional ram space to guests ?
( without using hugetblfs area, because we have so many guests and don't want to allocate all the ram for hugetblfs) 

Maybe we should do some work inside the linux guests ?

**Comment by sangjinhan** [comment]
To communicate with VM guests via vhost-user, BESS needs access to the VM memory. This is done by reading the shared mapped file (mem-path=/mnt/huge, share=on). I am not sure whether it must be backed by hugetlbfs, but at least it must be `memory-backend-file` and `share=on` so that BESS can read/write the memory (`-mem-prealloc` is also necessary I guess). `memory-backend-ram` would not work since it is not accessible by the BESS process.
